### ISSUE TITLE
Note sure this works anymore?

### ISSUE THREAD

**Issue by bradennapier** [aerian-studios/ignite-typescript-boilerplate#12]
```
an error occured while installing ignite-typescript-boilerplate boilerplate.
TypeError: Cannot read property 'dependencies' of undefined
    at mergePackageJsons (/Users/Shared/Development/projects/@bradennapier/IdexMobileIgnite/node_modules/ignite-typescript-boilerplate/boilerplate.js:185:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.install (/Users/Shared/Development/projects/@bradennapier/IdexMobileIgnite/node_modules/ignite-typescript-boilerplate/boilerplate.js:201:3)
error installing boilerplate
❯ 
```

**Comment by S-unya** [comment]
Hi, thanks for this. You are right, this needs some TLC. I will raise the issues in our team and see if I can get someone to work on it!
